/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: model.i

package model

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
extern void _wrap_Swig_free_model_65a646021e4d72ef(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_model_65a646021e4d72ef(swig_intgo arg1);
extern swig_intgo _wrap_ERR_SUCCESS_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_ERR_MALFORMED_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_ERR_DIVBYZERO_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_ERR_MISSBRACKET_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_ERR_NEGATIVEROOT_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_UNKNOWN_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_LBRACKET_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_RBRACKET_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_NUMBER_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_VARIABLE_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_PLUS_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_MINUS_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_MULTIPLY_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_DIVIDE_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_MOD_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_POWER_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_COS_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_SIN_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_TAN_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_ACOS_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_ASIN_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_ATAN_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_SQRT_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_LN_model_65a646021e4d72ef(void);
extern swig_intgo _wrap_VAL_LOG_model_65a646021e4d72ef(void);
extern void _wrap_item_t_value_set_model_65a646021e4d72ef(uintptr_t arg1, double arg2);
extern double _wrap_item_t_value_get_model_65a646021e4d72ef(uintptr_t arg1);
extern void _wrap_item_t_Xtype_set_model_65a646021e4d72ef(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_item_t_Xtype_get_model_65a646021e4d72ef(uintptr_t arg1);
extern uintptr_t _wrap_new_item_t_model_65a646021e4d72ef(void);
extern void _wrap_delete_item_t_model_65a646021e4d72ef(uintptr_t arg1);
extern uintptr_t _wrap_new_CalcModel_model_65a646021e4d72ef(void);
extern double _wrap_CalcModel_get_result_model_65a646021e4d72ef(uintptr_t arg1);
extern swig_intgo _wrap_CalcModel_calculate_model_65a646021e4d72ef(uintptr_t arg1, swig_type_1 arg2, double arg3);
extern void _wrap_delete_CalcModel_model_65a646021e4d72ef(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_model_65a646021e4d72ef(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_model_65a646021e4d72ef(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type Err_t int
func _swig_getERR_SUCCESS() (_swig_ret Err_t) {
	var swig_r Err_t
	swig_r = (Err_t)(C._wrap_ERR_SUCCESS_model_65a646021e4d72ef())
	return swig_r
}

var ERR_SUCCESS Err_t = _swig_getERR_SUCCESS()
func _swig_getERR_MALFORMED() (_swig_ret Err_t) {
	var swig_r Err_t
	swig_r = (Err_t)(C._wrap_ERR_MALFORMED_model_65a646021e4d72ef())
	return swig_r
}

var ERR_MALFORMED Err_t = _swig_getERR_MALFORMED()
func _swig_getERR_DIVBYZERO() (_swig_ret Err_t) {
	var swig_r Err_t
	swig_r = (Err_t)(C._wrap_ERR_DIVBYZERO_model_65a646021e4d72ef())
	return swig_r
}

var ERR_DIVBYZERO Err_t = _swig_getERR_DIVBYZERO()
func _swig_getERR_MISSBRACKET() (_swig_ret Err_t) {
	var swig_r Err_t
	swig_r = (Err_t)(C._wrap_ERR_MISSBRACKET_model_65a646021e4d72ef())
	return swig_r
}

var ERR_MISSBRACKET Err_t = _swig_getERR_MISSBRACKET()
func _swig_getERR_NEGATIVEROOT() (_swig_ret Err_t) {
	var swig_r Err_t
	swig_r = (Err_t)(C._wrap_ERR_NEGATIVEROOT_model_65a646021e4d72ef())
	return swig_r
}

var ERR_NEGATIVEROOT Err_t = _swig_getERR_NEGATIVEROOT()
type Val_t int
func _swig_getVAL_UNKNOWN() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_UNKNOWN_model_65a646021e4d72ef())
	return swig_r
}

var VAL_UNKNOWN Val_t = _swig_getVAL_UNKNOWN()
func _swig_getVAL_LBRACKET() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_LBRACKET_model_65a646021e4d72ef())
	return swig_r
}

var VAL_LBRACKET Val_t = _swig_getVAL_LBRACKET()
func _swig_getVAL_RBRACKET() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_RBRACKET_model_65a646021e4d72ef())
	return swig_r
}

var VAL_RBRACKET Val_t = _swig_getVAL_RBRACKET()
func _swig_getVAL_NUMBER() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_NUMBER_model_65a646021e4d72ef())
	return swig_r
}

var VAL_NUMBER Val_t = _swig_getVAL_NUMBER()
func _swig_getVAL_VARIABLE() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_VARIABLE_model_65a646021e4d72ef())
	return swig_r
}

var VAL_VARIABLE Val_t = _swig_getVAL_VARIABLE()
func _swig_getVAL_PLUS() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_PLUS_model_65a646021e4d72ef())
	return swig_r
}

var VAL_PLUS Val_t = _swig_getVAL_PLUS()
func _swig_getVAL_MINUS() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_MINUS_model_65a646021e4d72ef())
	return swig_r
}

var VAL_MINUS Val_t = _swig_getVAL_MINUS()
func _swig_getVAL_MULTIPLY() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_MULTIPLY_model_65a646021e4d72ef())
	return swig_r
}

var VAL_MULTIPLY Val_t = _swig_getVAL_MULTIPLY()
func _swig_getVAL_DIVIDE() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_DIVIDE_model_65a646021e4d72ef())
	return swig_r
}

var VAL_DIVIDE Val_t = _swig_getVAL_DIVIDE()
func _swig_getVAL_MOD() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_MOD_model_65a646021e4d72ef())
	return swig_r
}

var VAL_MOD Val_t = _swig_getVAL_MOD()
func _swig_getVAL_POWER() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_POWER_model_65a646021e4d72ef())
	return swig_r
}

var VAL_POWER Val_t = _swig_getVAL_POWER()
func _swig_getVAL_COS() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_COS_model_65a646021e4d72ef())
	return swig_r
}

var VAL_COS Val_t = _swig_getVAL_COS()
func _swig_getVAL_SIN() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_SIN_model_65a646021e4d72ef())
	return swig_r
}

var VAL_SIN Val_t = _swig_getVAL_SIN()
func _swig_getVAL_TAN() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_TAN_model_65a646021e4d72ef())
	return swig_r
}

var VAL_TAN Val_t = _swig_getVAL_TAN()
func _swig_getVAL_ACOS() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_ACOS_model_65a646021e4d72ef())
	return swig_r
}

var VAL_ACOS Val_t = _swig_getVAL_ACOS()
func _swig_getVAL_ASIN() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_ASIN_model_65a646021e4d72ef())
	return swig_r
}

var VAL_ASIN Val_t = _swig_getVAL_ASIN()
func _swig_getVAL_ATAN() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_ATAN_model_65a646021e4d72ef())
	return swig_r
}

var VAL_ATAN Val_t = _swig_getVAL_ATAN()
func _swig_getVAL_SQRT() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_SQRT_model_65a646021e4d72ef())
	return swig_r
}

var VAL_SQRT Val_t = _swig_getVAL_SQRT()
func _swig_getVAL_LN() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_LN_model_65a646021e4d72ef())
	return swig_r
}

var VAL_LN Val_t = _swig_getVAL_LN()
func _swig_getVAL_LOG() (_swig_ret Val_t) {
	var swig_r Val_t
	swig_r = (Val_t)(C._wrap_VAL_LOG_model_65a646021e4d72ef())
	return swig_r
}

var VAL_LOG Val_t = _swig_getVAL_LOG()
type SwigcptrItem_t uintptr

func (p SwigcptrItem_t) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrItem_t) SwigIsItem_t() {
}

func (arg1 SwigcptrItem_t) SetValue(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_item_t_value_set_model_65a646021e4d72ef(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrItem_t) GetValue() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_item_t_value_get_model_65a646021e4d72ef(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrItem_t) SetXtype(arg2 Val_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_item_t_Xtype_set_model_65a646021e4d72ef(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrItem_t) GetXtype() (_swig_ret Val_t) {
	var swig_r Val_t
	_swig_i_0 := arg1
	swig_r = (Val_t)(C._wrap_item_t_Xtype_get_model_65a646021e4d72ef(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewItem_t() (_swig_ret Item_t) {
	var swig_r Item_t
	swig_r = (Item_t)(SwigcptrItem_t(C._wrap_new_item_t_model_65a646021e4d72ef()))
	return swig_r
}

func DeleteItem_t(arg1 Item_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_item_t_model_65a646021e4d72ef(C.uintptr_t(_swig_i_0))
}

type Item_t interface {
	Swigcptr() uintptr
	SwigIsItem_t()
	SetValue(arg2 float64)
	GetValue() (_swig_ret float64)
	SetXtype(arg2 Val_t)
	GetXtype() (_swig_ret Val_t)
}

type SwigcptrCalcModel uintptr

func (p SwigcptrCalcModel) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrCalcModel) SwigIsCalcModel() {
}

func NewCalcModel() (_swig_ret CalcModel) {
	var swig_r CalcModel
	swig_r = (CalcModel)(SwigcptrCalcModel(C._wrap_new_CalcModel_model_65a646021e4d72ef()))
	return swig_r
}

func (arg1 SwigcptrCalcModel) Get_result() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_CalcModel_get_result_model_65a646021e4d72ef(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrCalcModel) Calculate(arg2 string, arg3 float64) (_swig_ret Err_t) {
	var swig_r Err_t
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Err_t)(C._wrap_CalcModel_calculate_model_65a646021e4d72ef(C.uintptr_t(_swig_i_0), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_1)), C.double(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func DeleteCalcModel(arg1 CalcModel) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_CalcModel_model_65a646021e4d72ef(C.uintptr_t(_swig_i_0))
}

type CalcModel interface {
	Swigcptr() uintptr
	SwigIsCalcModel()
	Get_result() (_swig_ret float64)
	Calculate(arg2 string, arg3 float64) (_swig_ret Err_t)
}


